build(report): cache pygmentize output

diff --git a/bin/pyg b/bin/pyg
--- a/bin/pyg
+++ b/bin/pyg
@@ -1,33 +1,38 @@
 #!/usr/bin/env bash
 bin="$(dirname $0)"
 root="$bin/.."
-report="$root/report"
+pyg="$root/report/pyg"
 
-Reset='\033[0m'
-BRed='\033[1;31m'
-BGreen='\033[1;32m'
-Yellow='\033[0;33m'
-BYellow='\033[1;33m'
-BBlue='\033[1;34m'
-IBlack='\033[0;90m'
+reset='\033[0m'
+red='\033[1;31m'
+green='\033[1;32m'
+yellow='\033[1;33m'
+blue='\033[1;34m'
+black='\033[0;90m'
 
 if ! [ -x "$(command -v pygmentize -V)" ]; then
-  echo -e "${BRed}error:${Reset} pygments is not installed. Install with ${BYellow}conda install pygments${Reset}"
+  echo -e "${red}error:${reset} pygments is not installed. Install with ${yellow}conda install pygments${reset}"
   exit 1
 fi
-
+mkdir -p $pyg
 # Copy definitions for LaTeX
-styles=$(python3 "$bin/pyg_styles")
-echo -e "${BBlue}generated: ${IBlack}styles${Reset}"
-
+if ! [ -f "$pyg/definitions.cache" ]; then
+  defs=$(python3 "$bin/pyg_defs")
+  echo "$defs" > "$pyg/definitions.cache"
+  echo -e "${blue}generated: ${black}defs${reset}"
+else
+  defs=$(<"$pyg/definitions.cache")
+fi
 # Generate syntax highlighting for Crystal files
 for file in $(find "$root/src" "$root/spec" \( -name '*.cr' -o -name '*.sh' \) -print)
 do
   FILE="${file#$root/}"
   DIR=$(dirname "${FILE}")
   NAME=$(basename "${FILE}" .cr)
-  mkdir -p "$report/pyg/$DIR"
-  echo "$styles" > "$report/pyg/$DIR/$NAME.tex"
-  pygmentize -f latex -O linenos=1,verboptions=numberblanklines=0 "$file" >> "$report/pyg/$DIR/$NAME.tex"
-  echo -e "${BGreen}pygmented: ${IBlack}$DIR/${Reset}${Yellow}$NAME.cr${Reset}"
+  if ! cmp --silent "$file" "$pyg/$DIR/$NAME.cache"; then
+    mkdir -p "$pyg/$DIR"
+    cp "$file" "$pyg/$DIR/$NAME.cache"
+    echo "$defs$(pygmentize -f latex -O linenos=1,verboptions=numberblanklines=0 $file)" > "$pyg/$DIR/$NAME.tex"
+    echo -e "${green}pygmented: ${black}$DIR/${reset}${yellow}$NAME.cr${reset}"
+  fi
 done
